import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { apiMutation, apiRequest } from '../../api/client';
import type { AcademicYear, Course } from '../../api/types';
import { PermissionGate } from '../../auth/PermissionGate';
import { EmptyState, ErrorNotice, Field, LoadingState, PageHeader, Panel, StatusBadge, SuccessNotice } from '../../components/Ui';
import { InstitutionTrail } from '../../components/InstitutionTrail';

const isoDate = (value: string) => value.slice(0, 10);

export function AcademicPage() {
  const { institutionId = '' } = useParams(); const client = useQueryClient(); const [success, setSuccess] = useState('');
  const years = useQuery({ queryKey: ['academic-years', institutionId], queryFn: async () => (await apiRequest<{ academicYears: AcademicYear[] }>(`/api/v1/institutions/${institutionId}/academic-years`)).academicYears, retry: false });
  const courses = useQuery({ queryKey: ['courses', institutionId], queryFn: async () => (await apiRequest<{ courses: Course[] }>(`/api/v1/courses?institutionId=${institutionId}`)).courses, retry: false });
  const refreshYears = () => client.invalidateQueries({ queryKey: ['academic-years', institutionId] }); const refreshCourses = () => client.invalidateQueries({ queryKey: ['courses', institutionId] });
  const createYear = useMutation({ mutationFn: (body: unknown) => apiMutation(`/api/v1/institutions/${institutionId}/academic-years`, 'POST', body), onSuccess: () => { setSuccess('Año lectivo creado.'); void refreshYears(); } });
  const updateYear = useMutation({ mutationFn: ({ id, body }: { id: string; body: unknown }) => apiMutation(`/api/v1/academic-years/${id}`, 'PATCH', body), onSuccess: () => { setSuccess('Año lectivo actualizado.'); void refreshYears(); } });
  const createCourse = useMutation({ mutationFn: (body: unknown) => apiMutation('/api/v1/courses', 'POST', body), onSuccess: () => { setSuccess('Curso creado.'); void refreshCourses(); } });
  const updateCourse = useMutation({ mutationFn: ({ id, body }: { id: string; body: unknown }) => apiMutation(`/api/v1/courses/${id}`, 'PATCH', body), onSuccess: () => { setSuccess('Curso actualizado.'); void refreshCourses(); } });
  const courseState = useMutation({ mutationFn: ({ id, active }: { id: string; active: boolean }) => apiMutation(`/api/v1/courses/${id}/${active ? 'reactivate' : 'deactivate'}`, 'POST'), onSuccess: () => { setSuccess('Estado del curso actualizado.'); void refreshCourses(); } });
  const yearSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); createYear.mutate({ label: String(data.get('label')), startsOn: String(data.get('startsOn')), endsOn: String(data.get('endsOn')), isCurrent: data.get('isCurrent') === 'on' }, { onSuccess: () => form.reset() }); };
  const courseSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const rawBtiYear = String(data.get('btiYear')); createCourse.mutate({ institutionId, academicYearId: String(data.get('academicYearId')), grade: String(data.get('grade')), section: String(data.get('section')), shift: String(data.get('shift')), btiYear: rawBtiYear === '' ? null : Number(rawBtiYear) }, { onSuccess: () => form.reset() }); };
  return <><InstitutionTrail /><PageHeader eyebrow="Paso 3 de 5" title="Año lectivo y cursos" description="Define el contexto temporal y luego organiza grado, sección y turno." />{success && <SuccessNotice>{success}</SuccessNotice>}
    <div className="two-column"><Panel title="Años lectivos" description="Solo uno puede estar marcado como actual."><PermissionGate permission="course.manage" resourceType="institution" resourceId={institutionId}><form className="stack-form" onSubmit={yearSubmit}><Field label="Etiqueta"><input name="label" placeholder="2026" required /></Field><div className="field-row"><Field label="Inicio"><input name="startsOn" type="date" required /></Field><Field label="Fin"><input name="endsOn" type="date" required /></Field></div><label className="check"><input name="isCurrent" type="checkbox" /> Establecer como año actual</label><button className="button primary" disabled={createYear.isPending}>Crear año lectivo</button>{createYear.error && <ErrorNotice error={createYear.error} />}</form></PermissionGate>{years.isLoading && <LoadingState />}{years.error && <ErrorNotice error={years.error} />}{years.data?.length === 0 && <EmptyState title="Sin años lectivos" description="Crea el contexto académico inicial." />}<div className="list-stack">{years.data?.map((year) => <div className="list-item" key={year.id}><div><strong>{year.label}</strong><small>{isoDate(year.startsOn)} — {isoDate(year.endsOn)}</small></div>{year.isCurrent ? <span className="badge badge-success">Actual</span> : <PermissionGate permission="course.manage" resourceType="institution" resourceId={institutionId}><button className="button small secondary" onClick={() => updateYear.mutate({ id: year.id, body: { isCurrent: true } })}>Hacer actual</button></PermissionGate>}</div>)}</div></Panel>
    <Panel title="Nuevo curso" description="La combinación año, grado, sección y turno es única."><PermissionGate permission="course.manage" resourceType="institution" resourceId={institutionId} fallback={<div className="notice">No tienes permiso para crear cursos.</div>}><form className="stack-form" onSubmit={courseSubmit}><Field label="Año lectivo"><select name="academicYearId" required defaultValue=""><option value="" disabled>Seleccionar…</option>{years.data?.map((year) => <option value={year.id} key={year.id}>{year.label}{year.isCurrent ? ' · actual' : ''}</option>)}</select></Field><div className="field-row"><Field label="Año / grado"><input name="grade" placeholder="7.º" required /></Field><Field label="Sección"><input name="section" placeholder="A" required /></Field></div><Field label="Turno"><input name="shift" placeholder="Mañana" required /></Field><Field label="Año BTI" hint="Opcional. Es necesario para resolver referencias curriculares por nivel."><select name="btiYear" defaultValue=""><option value="">Sin contexto BTI</option><option value="1">1.º BTI</option><option value="2">2.º BTI</option><option value="3">3.º BTI</option></select></Field><button className="button primary" disabled={createCourse.isPending}>Crear curso</button>{createCourse.error && <ErrorNotice error={createCourse.error} />}</form></PermissionGate></Panel></div>
    <section className="panel"><div className="panel-heading"><div><h2>Cursos</h2><p>Contextos disponibles para asignaciones docentes.</p></div></div>{courses.isLoading && <LoadingState />}{courses.error && <ErrorNotice error={courses.error} />}{courses.data?.length === 0 && <EmptyState title="Sin cursos" description="Crea un año lectivo y luego el primer curso." />}<div className="card-grid compact">{courses.data?.map((course) => <article className="entity-card" key={course.id}><div className="entity-card-top"><div><p className="eyebrow">{course.academicYear.label}</p><h3>{course.grade} · Sección {course.section}</h3><p>Turno {course.shift}{course.btiYear === null ? '' : ` · ${course.btiYear}.º BTI`}</p></div><StatusBadge active={course.isActive} /></div><Link className="button small secondary" to={`/admin/institutions/${institutionId}/courses/${course.id}/students`}>Estudiantes</Link><PermissionGate permission="course.manage" resourceType="course" resourceId={course.id}><div className="card-actions"><details className="inline-editor"><summary className="button small secondary">Editar</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const rawBtiYear = String(data.get('btiYear')); updateCourse.mutate({ id: course.id, body: { grade: String(data.get('grade')), section: String(data.get('section')), shift: String(data.get('shift')), btiYear: rawBtiYear === '' ? null : Number(rawBtiYear) } }); }}><Field label="Grado"><input name="grade" defaultValue={course.grade} /></Field><Field label="Sección"><input name="section" defaultValue={course.section} /></Field><Field label="Turno"><input name="shift" defaultValue={course.shift} /></Field><Field label="Año BTI"><select name="btiYear" defaultValue={course.btiYear ?? ''}><option value="">Sin contexto BTI</option><option value="1">1.º BTI</option><option value="2">2.º BTI</option><option value="3">3.º BTI</option></select></Field><button className="button small">Guardar</button></form></details><button className="button small danger-ghost" onClick={() => { if (window.confirm(course.isActive ? '¿Desactivar el curso?' : '¿Reactivar el curso?')) courseState.mutate({ id: course.id, active: !course.isActive }); }}>{course.isActive ? 'Desactivar' : 'Reactivar'}</button></div></PermissionGate></article>)}</div></section>{(updateYear.error || updateCourse.error || courseState.error) && <ErrorNotice error={updateYear.error ?? updateCourse.error ?? courseState.error} />}</>;
}
