import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent } from 'react';
import { useParams } from 'react-router-dom';
import { apiMutation, apiRequest } from '../../api/client';
import type { Course, Subject, Teacher, TeachingAssignment } from '../../api/types';
import { PermissionGate } from '../../auth/PermissionGate';
import { EmptyState, ErrorNotice, Field, LoadingState, PageHeader, StatusBadge, SuccessNotice } from '../../components/Ui';
import { InstitutionTrail } from '../../components/InstitutionTrail';

export function AssignmentsPage() {
  const { institutionId = '' } = useParams(); const client = useQueryClient(); const [success, setSuccess] = useState('');
  const teachers = useQuery({ queryKey: ['teachers', institutionId], queryFn: async () => (await apiRequest<{ teachers: Teacher[] }>(`/api/v1/institutions/${institutionId}/teachers`)).teachers, retry: false });
  const courses = useQuery({ queryKey: ['courses', institutionId], queryFn: async () => (await apiRequest<{ courses: Course[] }>(`/api/v1/courses?institutionId=${institutionId}`)).courses, retry: false });
  const subjects = useQuery({ queryKey: ['subjects', institutionId], queryFn: async () => (await apiRequest<{ subjects: Subject[] }>(`/api/v1/subjects?institutionId=${institutionId}`)).subjects, retry: false });
  const assignments = useQuery({ queryKey: ['assignments', institutionId], queryFn: async () => (await apiRequest<{ teachingAssignments: TeachingAssignment[] }>(`/api/v1/teaching-assignments?institutionId=${institutionId}&includeEnded=true`)).teachingAssignments, retry: false });
  const refresh = () => client.invalidateQueries({ queryKey: ['assignments', institutionId] });
  const create = useMutation({ mutationFn: (body: unknown) => apiMutation('/api/v1/teaching-assignments', 'POST', body), onSuccess: () => { setSuccess('Asignación docente creada.'); void refresh(); } });
  const state = useMutation({ mutationFn: ({ id, active }: { id: string; active: boolean }) => apiMutation(`/api/v1/teaching-assignments/${id}/${active ? 'reactivate' : 'retire'}`, 'POST'), onSuccess: () => { setSuccess('Estado de la asignación actualizado.'); void refresh(); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); create.mutate({ institutionId, teacherId: String(data.get('teacherId')), courseId: String(data.get('courseId')), subjectId: String(data.get('subjectId')) }, { onSuccess: () => form.reset() }); };
  const loadingDependencies = teachers.isLoading || courses.isLoading || subjects.isLoading;
  return <><InstitutionTrail /><PageHeader eyebrow="Paso 5 de 5" title="Asignaciones docentes" description="Une un docente, un curso y una materia dentro del mismo contexto institucional." />{success && <SuccessNotice>{success}</SuccessNotice>}
    <PermissionGate permission="teaching-assignment.manage" resourceType="institution" resourceId={institutionId} fallback={<div className="notice">Puedes consultar asignaciones, pero no administrarlas.</div>}><section className="panel accent-panel"><div className="panel-heading"><div><h2>Nueva asignación</h2><p>Solo se ofrecen docentes, cursos y materias activas.</p></div></div>{loadingDependencies ? <LoadingState label="Preparando opciones…" /> : <form className="form-grid assignment-form" onSubmit={submit}><Field label="Docente"><select name="teacherId" defaultValue="" required><option value="" disabled>Seleccionar…</option>{teachers.data?.filter((x) => x.isActive && x.institutions.some((link) => link.institutionId === institutionId && link.endedAt === null)).map((x) => <option value={x.id} key={x.id}>{x.displayName}</option>)}</select></Field><Field label="Curso"><select name="courseId" defaultValue="" required><option value="" disabled>Seleccionar…</option>{courses.data?.filter((x) => x.isActive).map((x) => <option value={x.id} key={x.id}>{x.grade} · {x.section} · {x.shift} ({x.academicYear.label})</option>)}</select></Field><Field label="Materia"><select name="subjectId" defaultValue="" required><option value="" disabled>Seleccionar…</option>{subjects.data?.filter((x) => x.isActive).map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select></Field><button className="button primary" disabled={create.isPending}>Asignar docente</button></form>}{create.error && <ErrorNotice error={create.error} />}</section></PermissionGate>
    <section className="panel"><div className="panel-heading"><div><h2>Asignaciones</h2><p>Las retiradas conservan el historial y pueden reactivarse si el contexto sigue vigente.</p></div></div>{assignments.isLoading && <LoadingState />}{assignments.error && <ErrorNotice error={assignments.error} />}{assignments.data?.length === 0 && <EmptyState title="Sin asignaciones" description="Completa los pasos anteriores y crea la primera asignación." />}<div className="table-wrap"><table><thead><tr><th>Docente</th><th>Curso</th><th>Materia</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{assignments.data?.map((item) => <tr key={item.id}><td><strong>{item.teacher.displayName}</strong></td><td>{item.course.grade} · {item.course.section}<small>{item.course.shift} · {item.course.academicYear.label}</small></td><td>{item.subject.name}</td><td><StatusBadge active={item.endedAt === null} activeLabel="Vigente" inactiveLabel="Retirada" /></td><td><PermissionGate permission="teaching-assignment.manage" resourceType="course" resourceId={item.courseId}><button className="button small danger-ghost" onClick={() => { const active = item.endedAt !== null; if (window.confirm(active ? '¿Reactivar esta asignación?' : '¿Retirar esta asignación sin borrar su historial?')) state.mutate({ id: item.id, active }); }}>{item.endedAt === null ? 'Retirar' : 'Reactivar'}</button></PermissionGate></td></tr>)}</tbody></table></div></section>{state.error && <ErrorNotice error={state.error} />}</>;
}
