import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent } from 'react';
import { useParams } from 'react-router-dom';
import { apiMutation, apiRequest } from '../../api/client';
import type { Subject } from '../../api/types';
import { PermissionGate } from '../../auth/PermissionGate';
import { EmptyState, ErrorNotice, Field, LoadingState, PageHeader, StatusBadge, SuccessNotice } from '../../components/Ui';
import { InstitutionTrail } from '../../components/InstitutionTrail';

export function SubjectsPage() {
  const { institutionId = '' } = useParams(); const client = useQueryClient(); const [success, setSuccess] = useState('');
  const query = useQuery({ queryKey: ['subjects', institutionId], queryFn: async () => (await apiRequest<{ subjects: Subject[] }>(`/api/v1/subjects?institutionId=${institutionId}`)).subjects, retry: false });
  const refresh = () => client.invalidateQueries({ queryKey: ['subjects', institutionId] });
  const create = useMutation({ mutationFn: (body: unknown) => apiMutation('/api/v1/subjects', 'POST', body), onSuccess: () => { setSuccess('Materia creada.'); void refresh(); } });
  const update = useMutation({ mutationFn: ({ id, body }: { id: string; body: unknown }) => apiMutation(`/api/v1/subjects/${id}`, 'PATCH', body), onSuccess: () => { setSuccess('Materia actualizada.'); void refresh(); } });
  const state = useMutation({ mutationFn: ({ id, active }: { id: string; active: boolean }) => apiMutation(`/api/v1/subjects/${id}/${active ? 'reactivate' : 'deactivate'}`, 'POST'), onSuccess: () => { setSuccess('Estado de la materia actualizado.'); void refresh(); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); create.mutate({ institutionId, name: String(data.get('name')) }, { onSuccess: () => form.reset() }); };
  return <><InstitutionTrail /><PageHeader eyebrow="Paso 4 de 5" title="Materias" description="Catálogo institucional genérico para asociar a los cursos." />{success && <SuccessNotice>{success}</SuccessNotice>}
    <PermissionGate permission="subject.manage" resourceType="institution" resourceId={institutionId} fallback={<div className="notice">Puedes consultar el catálogo, pero no modificarlo.</div>}><section className="panel"><div className="panel-heading"><div><h2>Nueva materia</h2><p>Catálogo institucional genérico. La referencia curricular se administrará mediante correspondencias separadas.</p></div></div><form className="form-grid" onSubmit={submit}><Field label="Nombre"><input name="name" required /></Field><button className="button primary" disabled={create.isPending}>Crear materia</button></form>{create.error && <ErrorNotice error={create.error} />}</section></PermissionGate>
    <section className="panel"><div className="panel-heading"><div><h2>Catálogo</h2><p>{query.data?.length ?? 0} materias visibles.</p></div></div>{query.isLoading && <LoadingState />}{query.error && <ErrorNotice error={query.error} />}{query.data?.length === 0 && <EmptyState title="Sin materias" description="Agrega la primera materia institucional." />}<div className="card-grid compact">{query.data?.map((subject) => <article className="entity-card" key={subject.id}><div className="entity-card-top"><div><h3>{subject.name}</h3><p>Materia institucional</p></div><StatusBadge active={subject.isActive} /></div><PermissionGate permission="subject.manage" resourceType="institution" resourceId={institutionId}><div className="card-actions"><details className="inline-editor"><summary className="button small secondary">Editar</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); update.mutate({ id: subject.id, body: { name: String(data.get('name')) } }); }}><Field label="Nombre"><input name="name" defaultValue={subject.name} required /></Field><button className="button small">Guardar</button></form></details><button className="button small danger-ghost" onClick={() => { if (window.confirm(subject.isActive ? '¿Desactivar la materia?' : '¿Reactivar la materia?')) state.mutate({ id: subject.id, active: !subject.isActive }); }}>{subject.isActive ? 'Desactivar' : 'Reactivar'}</button></div></PermissionGate></article>)}</div></section>{(update.error || state.error) && <ErrorNotice error={update.error ?? state.error} />}</>;
}
