import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent } from 'react';
import { useParams } from 'react-router-dom';
import { apiMutation, apiRequest } from '../../api/client';
import type { CurriculumDisciplineReference, CursorPage, Subject, SubjectCurriculumMapping } from '../../api/types';
import { PermissionGate } from '../../auth/PermissionGate';
import { EmptyState, ErrorNotice, Field, LoadingState, PageHeader, StatusBadge, SuccessNotice } from '../../components/Ui';
import { InstitutionTrail } from '../../components/InstitutionTrail';

function CurriculumReference({ institutionId, subject }: { institutionId: string; subject: Subject }) {
  const client = useQueryClient();
  const [success, setSuccess] = useState('');
  const base = `/api/v1/institutions/${institutionId}/subjects/${subject.id}/curriculum-mappings`;
  const mappings = useQuery({ queryKey: ['curriculum-mappings', institutionId, subject.id], queryFn: () => apiRequest<CursorPage<SubjectCurriculumMapping>>(`${base}?status=current&limit=100`) });
  const disciplines = useQuery({ queryKey: ['curriculum-disciplines', institutionId], queryFn: () => apiRequest<CursorPage<CurriculumDisciplineReference>>(`/api/v1/curriculum/disciplines?institutionId=${institutionId}&limit=100`) });
  const refresh = () => client.invalidateQueries({ queryKey: ['curriculum-mappings', institutionId, subject.id] });
  const create = useMutation({ mutationFn: (body: { btiYear: number; curriculumDisciplineId: string }) => apiMutation<{ data: SubjectCurriculumMapping }>(base, 'POST', body), onSuccess: () => { setSuccess('Referencia curricular creada.'); void refresh(); } });
  const retire = useMutation({ mutationFn: (mapping: SubjectCurriculumMapping) => apiMutation(`${base}/${mapping.id}/retire`, 'POST', { expectedVersion: mapping.rowVersion }), onSuccess: () => { setSuccess('Referencia curricular retirada; su historia se conserva.'); void refresh(); } });
  const replace = useMutation({ mutationFn: ({ mapping, curriculumDisciplineId }: { mapping: SubjectCurriculumMapping; curriculumDisciplineId: string }) => apiMutation(`${base}/${mapping.id}/replace`, 'POST', { curriculumDisciplineId, expectedVersion: mapping.rowVersion }), onSuccess: () => { setSuccess('Referencia curricular sustituida.'); void refresh(); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); create.mutate({ btiYear: Number(data.get('btiYear')), curriculumDisciplineId: String(data.get('curriculumDisciplineId')) }, { onSuccess: () => form.reset() }); };

  return <section className="curriculum-reference" aria-label={`Referencia curricular de ${subject.name}`}>
    <div className="curriculum-reference-heading"><div><strong>Referencia curricular</strong><small>Correspondencia opcional por año BTI.</small></div></div>
    {success && <SuccessNotice>{success}</SuccessNotice>}
    {mappings.isLoading && <LoadingState label="Consultando referencias…" />}{mappings.error && <ErrorNotice error={mappings.error} />}
    {mappings.data?.data.length === 0 && <EmptyState title="Sin referencia curricular" description="La materia puede utilizarse normalmente sin correspondencia." />}
    <div className="curriculum-list">{mappings.data?.data.map((mapping) => <div className="curriculum-item" key={mapping.id}><div><strong>{mapping.btiYear}.º BTI · {mapping.discipline.officialName}</strong><small>{mapping.discipline.planType.name} · {mapping.discipline.academicArea?.name ?? 'Área académica aún no validada'}</small><small>Disponibilidad de malla aún no consultable</small></div><PermissionGate permission="subject-curriculum-mapping.manage" resourceType="institution" resourceId={institutionId}><div className="row-actions"><details className="inline-editor"><summary className="button small secondary">Sustituir</summary><form onSubmit={(event) => { event.preventDefault(); replace.mutate({ mapping, curriculumDisciplineId: String(new FormData(event.currentTarget).get('curriculumDisciplineId')) }); }}><Field label="Disciplina curricular"><select name="curriculumDisciplineId" required defaultValue=""><option value="" disabled>Seleccionar…</option>{disciplines.data?.data.filter((item) => item.id !== mapping.curriculumDisciplineId).map((item) => <option key={item.id} value={item.id}>{item.officialName}</option>)}</select></Field><button className="button small" disabled={replace.isPending}>Confirmar sustitución</button></form></details><button className="button small danger-ghost" disabled={retire.isPending} onClick={() => { if (window.confirm('¿Retirar esta referencia? La historia se conservará.')) retire.mutate(mapping); }}>Retirar</button></div></PermissionGate></div>)}</div>
    <PermissionGate permission="subject-curriculum-mapping.manage" resourceType="institution" resourceId={institutionId}><form className="curriculum-create" onSubmit={submit}><Field label="Año BTI"><select name="btiYear" required defaultValue=""><option value="" disabled>Seleccionar…</option><option value="1">1.º BTI</option><option value="2">2.º BTI</option><option value="3">3.º BTI</option></select></Field><Field label="Disciplina curricular"><select name="curriculumDisciplineId" required defaultValue=""><option value="" disabled>Seleccionar…</option>{disciplines.data?.data.map((item) => <option key={item.id} value={item.id}>{item.officialName}</option>)}</select></Field><button className="button small primary" disabled={create.isPending || disciplines.data?.data.length === 0}>Añadir referencia</button></form></PermissionGate>
    {disciplines.error && <ErrorNotice error={disciplines.error} />}{(create.error || retire.error || replace.error) && <ErrorNotice error={create.error ?? retire.error ?? replace.error} />}
  </section>;
}

export function SubjectsPage() {
  const { institutionId = '' } = useParams(); const client = useQueryClient(); const [success, setSuccess] = useState('');
  const query = useQuery({ queryKey: ['subjects', institutionId], queryFn: async () => (await apiRequest<{ subjects: Subject[] }>(`/api/v1/subjects?institutionId=${institutionId}`)).subjects });
  const refresh = () => client.invalidateQueries({ queryKey: ['subjects', institutionId] });
  const create = useMutation({ mutationFn: (body: unknown) => apiMutation('/api/v1/subjects', 'POST', body), onSuccess: () => { setSuccess('Materia creada.'); void refresh(); } });
  const update = useMutation({ mutationFn: ({ id, body }: { id: string; body: unknown }) => apiMutation(`/api/v1/subjects/${id}`, 'PATCH', body), onSuccess: () => { setSuccess('Materia actualizada.'); void refresh(); } });
  const state = useMutation({ mutationFn: ({ id, active }: { id: string; active: boolean }) => apiMutation(`/api/v1/subjects/${id}/${active ? 'reactivate' : 'deactivate'}`, 'POST'), onSuccess: () => { setSuccess('Estado de la materia actualizado.'); void refresh(); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); create.mutate({ institutionId, name: String(data.get('name')) }, { onSuccess: () => form.reset() }); };
  return <><InstitutionTrail /><PageHeader eyebrow="Paso 4 de 5" title="Materias" description="Catálogo institucional genérico con referencias curriculares opcionales y separadas." />{success && <SuccessNotice>{success}</SuccessNotice>}
    <PermissionGate permission="subject.manage" resourceType="institution" resourceId={institutionId} fallback={<div className="notice">Puedes consultar el catálogo, pero no modificarlo.</div>}><section className="panel"><div className="panel-heading"><div><h2>Nueva materia</h2><p>La materia no necesita una referencia curricular para existir o utilizarse.</p></div></div><form className="form-grid" onSubmit={submit}><Field label="Nombre"><input name="name" required /></Field><button className="button primary" disabled={create.isPending}>Crear materia</button></form>{create.error && <ErrorNotice error={create.error} />}</section></PermissionGate>
    <section className="panel"><div className="panel-heading"><div><h2>Catálogo</h2><p>{query.data?.length ?? 0} materias visibles.</p></div></div>{query.isLoading && <LoadingState />}{query.error && <ErrorNotice error={query.error} />}{query.data?.length === 0 && <EmptyState title="Sin materias" description="Agrega la primera materia institucional." />}<div className="card-grid compact">{query.data?.map((subject) => <article className="entity-card" key={subject.id}><div className="entity-card-top"><div><h3>{subject.name}</h3><p>Materia institucional</p></div><StatusBadge active={subject.isActive} /></div><PermissionGate permission="subject.manage" resourceType="institution" resourceId={institutionId}><div className="card-actions"><details className="inline-editor"><summary className="button small secondary">Editar</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); update.mutate({ id: subject.id, body: { name: String(data.get('name')) } }); }}><Field label="Nombre"><input name="name" defaultValue={subject.name} required /></Field><button className="button small">Guardar</button></form></details><button className="button small danger-ghost" onClick={() => { if (window.confirm(subject.isActive ? '¿Desactivar la materia?' : '¿Reactivar la materia?')) state.mutate({ id: subject.id, active: !subject.isActive }); }}>{subject.isActive ? 'Desactivar' : 'Reactivar'}</button></div></PermissionGate><PermissionGate permission="subject-curriculum-mapping.read" resourceType="institution" resourceId={institutionId} fallback={<div className="curriculum-reference"><strong>Referencia curricular</strong><small>No disponible con los permisos actuales.</small></div>}><CurriculumReference institutionId={institutionId} subject={subject} /></PermissionGate></article>)}</div></section>{(update.error || state.error) && <ErrorNotice error={update.error ?? state.error} />}</>;
}
