import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent } from 'react';
import { useParams } from 'react-router-dom';
import { apiMutation, apiRequest } from '../../api/client';
import type { Teacher } from '../../api/types';
import { PermissionGate } from '../../auth/PermissionGate';
import { EmptyState, ErrorNotice, Field, LoadingState, PageHeader, StatusBadge, SuccessNotice } from '../../components/Ui';
import { InstitutionTrail } from '../../components/InstitutionTrail';

export function TeachersPage() {
  const { institutionId = '' } = useParams(); const client = useQueryClient(); const [mode, setMode] = useState<'NEW' | 'EXISTING'>('NEW'); const [success, setSuccess] = useState('');
  const query = useQuery({ queryKey: ['teachers', institutionId], queryFn: async () => (await apiRequest<{ teachers: Teacher[] }>(`/api/v1/institutions/${institutionId}/teachers`)).teachers, retry: false });
  const refresh = () => client.invalidateQueries({ queryKey: ['teachers', institutionId] });
  const create = useMutation({ mutationFn: (body: unknown) => apiMutation(`/api/v1/institutions/${institutionId}/teachers`, 'POST', body), onSuccess: () => { setSuccess('Docente, cuenta y vínculo institucional creados correctamente.'); void refresh(); } });
  const update = useMutation({ mutationFn: ({ id, displayName }: { id: string; displayName: string }) => apiMutation(`/api/v1/institutions/${institutionId}/teachers/${id}`, 'PATCH', { displayName }), onSuccess: () => { setSuccess('Docente actualizado.'); void refresh(); } });
  const changeState = useMutation({ mutationFn: ({ id, active }: { id: string; active: boolean }) => apiMutation(`/api/v1/institutions/${institutionId}/teachers/${id}/${active ? 'reactivate' : 'deactivate'}`, 'POST'), onSuccess: () => { setSuccess('Estado del docente actualizado.'); void refresh(); } });
  const link = useMutation({ mutationFn: ({ id, active }: { id: string; active: boolean }) => apiMutation(`/api/v1/institutions/${institutionId}/teachers/${id}/${active ? 'link' : 'unlink'}`, 'POST'), onSuccess: () => { setSuccess('Vínculo institucional actualizado.'); void refresh(); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const account = mode === 'NEW' ? { kind: 'NEW', login: String(data.get('login')), password: String(data.get('password')) } : { kind: 'EXISTING', userId: String(data.get('userId')) }; create.mutate({ displayName: String(data.get('displayName')), account }, { onSuccess: () => form.reset() }); };
  return <><InstitutionTrail /><PageHeader eyebrow="Paso 2 de 5" title="Docentes y acceso" description="Crea el perfil, la cuenta de acceso y el vínculo institucional en una sola operación." />{success && <SuccessNotice>{success}</SuccessNotice>}
    <PermissionGate permission="teacher.manage" resourceType="institution" resourceId={institutionId} fallback={<div className="notice">Puedes consultar docentes, pero no administrarlos.</div>}><section className="panel"><div className="panel-heading"><div><h2>Registrar docente</h2><p>La contraseña solo se envía al backend y nunca vuelve a mostrarse.</p></div><div className="segmented"><button type="button" className={mode === 'NEW' ? 'active' : ''} onClick={() => setMode('NEW')}>Cuenta nueva</button><button type="button" className={mode === 'EXISTING' ? 'active' : ''} onClick={() => setMode('EXISTING')}>Cuenta existente</button></div></div><form className="form-grid" onSubmit={submit}><Field label="Nombre completo"><input name="displayName" required /></Field>{mode === 'NEW' ? <><Field label="Usuario"><input name="login" required autoComplete="off" /></Field><Field label="Contraseña inicial" hint="Mínimo 12 caracteres"><input name="password" type="password" minLength={12} required autoComplete="new-password" /></Field></> : <Field label="UUID del usuario"><input name="userId" required /></Field>}<button className="button primary" disabled={create.isPending}>{create.isPending ? 'Creando…' : 'Crear docente'}</button></form>{create.error && <ErrorNotice error={create.error} />}</section></PermissionGate>
    <section className="panel"><div className="panel-heading"><div><h2>Directorio docente</h2><p>{query.data?.length ?? 0} perfiles visibles en esta institución.</p></div></div>{query.isLoading && <LoadingState />}{query.error && <ErrorNotice error={query.error} />}{query.data?.length === 0 && <EmptyState title="Aún no hay docentes" description="Registra el primer perfil y su cuenta de acceso." />}<div className="table-wrap"><table><thead><tr><th>Docente</th><th>Usuario</th><th>Vínculo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{query.data?.map((teacher) => { const currentLink = teacher.institutions.find((item) => item.institutionId === institutionId); const linked = Boolean(currentLink && currentLink.endedAt === null); return <tr key={teacher.id}><td><strong>{teacher.displayName}</strong><small>{teacher.id.slice(0, 8)}</small></td><td>{teacher.user.login}</td><td><StatusBadge active={linked} activeLabel="Vinculado" inactiveLabel="Desvinculado" /></td><td><StatusBadge active={teacher.isActive} /></td><td><PermissionGate permission="teacher.manage" resourceType="institution" resourceId={institutionId}><div className="row-actions"><details className="inline-editor"><summary className="button small secondary">Editar</summary><form onSubmit={(event) => { event.preventDefault(); update.mutate({ id: teacher.id, displayName: String(new FormData(event.currentTarget).get('displayName')) }); }}><Field label="Nombre"><input name="displayName" defaultValue={teacher.displayName} required /></Field><button className="button small">Guardar</button></form></details><button className="button small secondary" onClick={() => { if (window.confirm(linked ? '¿Desvincular al docente de la institución?' : '¿Restablecer el vínculo institucional?')) link.mutate({ id: teacher.id, active: !linked }); }}>{linked ? 'Desvincular' : 'Vincular'}</button><button className="button small danger-ghost" onClick={() => { if (window.confirm(teacher.isActive ? '¿Desactivar al docente y revocar sus sesiones?' : '¿Reactivar al docente?')) changeState.mutate({ id: teacher.id, active: !teacher.isActive }); }}>{teacher.isActive ? 'Desactivar' : 'Reactivar'}</button></div></PermissionGate></td></tr>; })}</tbody></table></div></section>
    {(update.error || changeState.error || link.error) && <ErrorNotice error={update.error ?? changeState.error ?? link.error} />}</>;
}
